export const TYPE_ITEM = {
    PAGE: 'PAGE',
    NOTEBOOK: 'NOTEBOOK',
};

export const ACTION = {
    NOTEBOOK_ADD : "NOTEBOOK_ADD",
    PAGE_ADD : "PAGE_ADD",
    PAGE_SELECT : "PAGE_SELECT",
    NOTEBOOK_SELECT: "NOTEBOOK_SELECT",
    NOTEBOOK_DELETE: "NOTEBOOK_DELETE",
    NOTEBOOK_EDIT: "NOTEBOOK_EDIT",
    NOTES_SAVE_NOTE: "NOTES_SAVE_NOTE",
    LOGIN_START: "LOGIN_START",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_ERROR: "LOGIN_ERROR",
    SIGNUP_ERROR: "SIGNUP_ERROR",
    SIGNUP_START: "SIGNUP_START",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_START: "LOGOUT_START",
    LOGOUT_ERROR: "LOGOUT_ERROR",
    DETECT_LOGGED_IN: "DETECT_LOGGED_IN",
    DETECT_LOGGED_OUT: "DETECT_LOGGED_OUT",
    NOTEBOOK_ADD_START: "NOTEBOOK_ADD_START",
    NOTEBOOK_ADD_SUCCESS: "NOTEBOOK_ADD_SUCCESS",
    NOTEBOOK_ADD_ERROR: "NOTEBOOK_ADD_ERROR",
    NOTEBOOK_DELETE_START: "NOTEBOOK_DELETE_START",
    NOTEBOOK_DELETE_SUCCESS: "NOTEBOOK_DELETE_SUCCESS",
    NOTEBOOK_DELETE_ERROR: "NOTEBOOK_DELETE_ERROR",
    PAGE_ADD_START: "PAGE_ADD_START",
    PAGE_ADD_SUCCESS:"PAGE_ADD_SUCCESS",
    PAGE_ADD_ERROR: "PAGE_ADD_ERROR",

};


export const monthNames = ["Jan", "Feb", "Mar", "Apr", "May", "Jun",
    "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"
];

